In [1]:
from learning import FederatedLearning
import numpy as np

## Local learning

In [2]:
fl_nn_ckks = FederatedLearning(3, "MLP", "ckks")

In [3]:
mse = fl_nn_ckks.local_learning_mse()

Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
MSE 1: 4675.640941727287
MSE 2: 4829.549278663267
MSE 3: 4575.008973500496
Mean MSE : 4693.399731297017
Execution Time : 0.42256808280944824


In [4]:
fl_nn_pail = FederatedLearning(3, "MLP", "paillier")

In [5]:
mse = fl_nn_pail.local_learning_mse()

Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
MSE 1: 4675.640941727287
MSE 2: 4829.549278663267
MSE 3: 4575.008973500496
Mean MSE : 4693.399731297017
Execution Time : 0.4754149913787842


In [6]:
fl_lreg_ckks = FederatedLearning(3, "lreg", "ckks")

In [7]:
mse = fl_lreg_ckks.local_learning_mse()

Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
MSE 1: 3639.461090942854
MSE 2: 4286.404514947821
MSE 3: 3951.616217404826
Mean MSE : 3959.160607765167
Execution Time : 0.012866973876953125


In [8]:
fl_lreg_pail = FederatedLearning(3, "lreg", "paillier")

In [9]:
mse = fl_lreg_pail.local_learning_mse()

Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
Iteration : 0
Iteration : 250
MSE 1: 3639.461090942854
MSE 2: 4286.404514947821
MSE 3: 3951.616217404826
Mean MSE : 3959.160607765167
Execution Time : 0.017126083374023438


## Federated Learning

#### Test chiffrage/déchiffrage gradients

In [4]:
fl2 = FederatedLearning(3, "MLP", "ckks")

In [5]:
grad = fl2.clients[0].compute_gradient()
grad2 = fl2.clients[1].compute_gradient()

In [6]:
grad

[array([[-4.30559129e-01, -2.15257704e-01, -2.68746924e+00,
         -2.05375171e+00, -1.89424431e+00, -1.81000996e+00,
          3.25244999e+00, -3.79414487e+00, -4.56061316e+00,
         -2.26868057e+00, -3.06981812e+02]]),
 array([-306.98178101])]

In [7]:
grad2

[array([[  -3.19530845,   -0.71525609,   -4.06607485,   -4.6958909 ,
           -1.08900201,   -0.91706306,    4.43101025,   -3.99649882,
           -4.63939524,   -3.56659293, -315.22467041]]),
 array([-315.22470093])]

In [8]:
sum_grad = []
for i in range(len(grad)):
    sum_grad.append(grad[i] + grad2[i])

In [9]:
sum_grad

[array([[  -3.62586758,   -0.9305138 ,   -6.75354409,   -6.74964261,
           -2.98324633,   -2.72707301,    7.68346024,   -7.79064369,
           -9.20000839,   -5.8352735 , -622.20648193]]),
 array([-622.20648193])]

In [10]:
egs = fl2.clients[0].encrypt.encrypt_gradients(grad)
egs2 = fl2.clients[1].encrypt.encrypt_gradients(grad2)

In [11]:
sum_egs = fl2.clients[1].encrypt.sum_encrypted_gradients(egs, egs2)

In [12]:
sum_gs = fl2.server.give_clear_gradient(sum_egs)

In [13]:
sum_gs

[array([[  -3.62586758,   -0.9305138 ,   -6.75354409,   -6.74964261,
           -2.98324633,   -2.72707301,    7.68346024,   -7.79064369,
           -9.20000839,   -5.8352735 , -622.20648193]]),
 array([-622.20648193])]

### Test FL

In [10]:
fl2 = FederatedLearning(3, "MLP", "ckks")
mse2 = fl2.federated_learning_mse()

Iteration 0
Iteration 50
Iteration 100
Iteration 150
Iteration 200
Iteration 250
Iteration 300
Iteration 350
Iteration 400
Iteration 450
MSE 1: 4680.519075894104
MSE 2: 4680.519075894104
MSE 3: 4680.519075894104
Mean MSE : 4680.519075894104
Execution Time : 35.688886880874634


Amélioration de la performance : a retest : a début j'avais oublié de diviser par n_clients et j'ai eu un meilleur res

In [7]:
fl4 = FederatedLearning(3, "MLP", "paillier")
mse4 = fl4.federated_learning_mse()

Iteration 0
Iteration 50
Iteration 100
Iteration 150
Iteration 200
Iteration 250
Iteration 300
Iteration 350
Iteration 400
Iteration 450
MSE 1: 4688.575316484701
MSE 2: 4682.468534558458
MSE 3: 4668.669984588702
Execution Time : 267.5012791156769


In [11]:
fl3 = FederatedLearning(3, "lreg", "ckks")
mse3 = fl3.federated_learning_mse()

Iteration 0
Iteration 50
Iteration 100
Iteration 150
Iteration 200
Iteration 250
Iteration 300
Iteration 350
Iteration 400
Iteration 450
MSE 1: 3883.0301445674118
MSE 2: 3883.0301445674118
MSE 3: 3883.0301445674118
Mean MSE : 3883.0301445674118
Execution Time : 29.271847248077393


Amélioration des performances

In [6]:
fl5 = FederatedLearning(3, "lreg", "paillier")
mse5 = fl5.federated_learning_mse()

Iteration 0
Iteration 50
Iteration 100
Iteration 150
Iteration 200
Iteration 250
Iteration 300
Iteration 350
Iteration 400
Iteration 450
MSE 1: 3883.0301445674386
MSE 2: 3883.0301445674386
MSE 3: 3883.0301445674386
Execution Time : 247.03608918190002


Amélioration des perfs. Pareil que pour lreg CKKS. Mais 8x plus long.